name: SyntheMol

channels:
  - conda-forge
  - rdkit
  - pytorch

dependencies:
  - python>=3.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch
  - rdkit
  - scikit-learn
  - scipy
  - tqdm
  - pip:
    - chemprop
    - typed-argument-parser

# TODO: make chem_utils on PyPI and then add it here
