name: combinatorial_antibiotics

channels:
  - conda-forge
  - rdkit

dependencies:
  - python>=3.9
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - rdkit
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - tqdm
  - pip:
    - typed-argument-parser
    - git+https://github.com/bp-kelley/descriptastorus
