name: combinatorial_antibiotics

channels:
  - conda-forge
  - rdkit

dependencies:
  - python>=3.7
  - ipdb
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - rdkit
  - scikit-learn
  - scipy
  - tqdm
  - pip:
      - typed-argument-parser
